import React from 'react';
import { Code, Zap, Palette } from 'lucide-react';

const Hero: React.FC = () => {
  return (
      <section className="py-16 md:py-24 hero-pattern relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-mesh"></div>
                  <div className="container mx-auto px-4 text-center relative z-10">
                          <div className="mb-12 animate-float">
                                    <Code size={48} className="text-blue-600 dark:text-blue-400 inline-block mb-4" />
                                            </div>
                                                    <h1 className="text-5xl md:text-6xl font-bold mb-8 leading-tight">
                                                              <span className="text-gradient">Commandez votre site web</span>
                                                                        <br />
                                                                                  <span className="text-gray-900 dark:text-white">personnalisé avec Famous-Tech !</span>
                                                                                          </h1>
                                                                                                  <p className="text-xl md:text-2xl text-gray-700 dark:text-gray-300 max-w-3xl mx-auto mb-12 leading-relaxed">
                                                                                                            Basée en Haïti, Famous-Tech est spécialisée dans la création de sites web sur mesure pour répondre à vos besoins spécifiques.
                                                                                                                    </p>
                                                                                                                            
                                                                                                                                    <div className="flex flex-wrap justify-center gap-6 mb-16">
                                                                                                                                              <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg flex flex-col items-center max-w-xs card-hover transform transition-all duration-300 border border-blue-50 dark:border-blue-900/20">
                                                                                                                                                          <div className="w-20 h-20 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center mb-5 animate-pulse-slow">
                                                                                                                                                                        <Zap size={32} className="text-white" />
                                                                                                                                                                                    </div>
                                                                                                                                                                                                <h3 className="text-xl font-bold mb-3 text-gray-800 dark:text-white">Landing Page</h3>
                                                                                                                                                                                                            <p className="text-gray-600 dark:text-gray-300 text-center">Pages d'atterrissage optimisées pour la conversion et l'engagement des visiteurs</p>
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                          <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg flex flex-col items-center max-w-xs card-hover transform transition-all duration-300 border border-indigo-50 dark:border-indigo-900/20">
                                                                                                                                                                                                                                                      <div className="w-20 h-20 bg-gradient-to-br from-indigo-400 to-indigo-600 rounded-full flex items-center justify-center mb-5 animate-pulse-slow">
                                                                                                                                                                                                                                                                    <Code size={32} className="text-white" />
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                            <h3 className="text-xl font-bold mb-3 text-gray-800 dark:text-white">Blog</h3>
                                                                                                                                                                                                                                                                                                        <p className="text-gray-600 dark:text-gray-300 text-center">Blogs professionnels pour partager votre contenu et établir votre expertise</p>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg flex flex-col items-center max-w-xs card-hover transform transition-all duration-300 border border-purple-50 dark:border-purple-900/20">
                                                                                                                                                                                                                                                                                                                                                  <div className="w-20 h-20 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center mb-5 animate-pulse-slow">
                                                                                                                                                                                                                                                                                                                                                                <Palette size={32} className="text-white" />
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-xl font-bold mb-3 text-gray-800 dark:text-white">Site Vitrine</h3>
                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-600 dark:text-gray-300 text-center">Sites vitrines élégants pour présenter votre entreprise et vos services</p>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="absolute -top-10 -left-10 w-40 h-40 bg-blue-200 dark:bg-blue-900/30 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-float"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute -bottom-10 -right-10 w-40 h-40 bg-purple-200 dark:bg-purple-900/30 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-float"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="bg-gradient-to-r from-blue-600 to-purple-600 text-white font-bold py-4 px-8 rounded-full text-lg shadow-lg hover:shadow-xl transform hover:-translate-y-1 transition-all duration-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Contactez-nous
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Hero;